Feature/sdka 7
seamlesspay/seamlesspay-android pull request #52
Opened 2022-11-22 16:54 UTC by TrayEdge

## Sentry Java SDK was added into the project. 

## Sentry SDK dependency was added into all 3 modules. It is initialised inside each other them with provided Sentry dns. Sentry Java SDK was chosen to reducer a probability of conflicts if the client will use Sentry Android SDK.

## We want to track crashed for SDK.

## We tested it with test exceptions throws and we was able to observe them inside Sentry Dashboard.

2022-12-09 18:58 UTC, dim-ser approved these changes
Maybe we can move "https://f3ca34981162465cabb2783483179ae9@o4504125304209408.ingest.sentry.io/4504140012584960" to the config class as a constant and reuse it in different places ?
But it's just an advice.

2022-12-13 17:58 UTC, IvanK88 requested changes

2022-12-20 14:47 UTC, TrayEdge commented on Client/src/main/java/com/seamlesspay/api/SeamlesspayFragment.java
> +  private void setUpSentry() {
The problem is that this code is used three times in different modules which are independent and can be used separately. This is why we can not share it. The only solution for now would be to create a separate shared module and put this method there. But, we will need to add Sentry dependency into this module. Maybe, in a future when we will have more additional configs we can create a shared module to put everything there.

2022-12-20 14:50 UTC, TrayEdge commented on CardForm/src/main/java/com/seamlesspay/cardform/view/CardForm.java
> +    options.setDsn("https://f3ca34981162465cabb2783483179ae9@o4504125304209408.ingest.sentry.io/4504140012584960");
Not at this point, the situation is the same as with comment below - this part of code is used in separate modules. We can move this string as a constant to the separate file, but in this case we will need to create three files for each module or create a shared module. This is something that we can discuss later in terms of our future plans for the library itself.

2022-12-20 14:52 UTC, TrayEdge commented
> Maybe we can move "https://f3ca34981162465cabb2783483179ae9@o4504125304209408.ingest.sentry.io/4504140012584960" to the config class as a constant and reuse it in different places ?
> But it's just an advice.

This is a good point, we will definitely do it in the future, for now all the different places where this string is used are in a separate modules and can not be accessed from each other. Please, check my other replays.

2022-12-28 13:46 UTC, IvanK88 approved these changes

2022-12-29 15:42 UTC, merged